/**
 * Copies third-party browser assets into `src/web/vendor/`.
 *
 * The frontend has no build step and the server has no runtime dependencies,
 * so the libraries it needs are vendored as plain files. Re-run this after
 * bumping `marked`, `dompurify`, `prismjs`, or `mermaid`.
 *
 *   npm run vendor
 */

import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));
const vendorDir = join(root, "src", "web", "vendor");

interface CopySpec {
  kind: "esm";
  from: string;
  to: string;
}

interface BundleSpec {
  kind: "bundle";
  to: string;
  from: string[];
  banner: string;
}

type Spec = CopySpec | BundleSpec;

/** Languages we preload into Prism; anything else renders unhighlighted. */
const PRISM_LANGUAGES = [
  "bash",
  "java",
  "python",
  "typescript",
  "json",
  "yaml",
  "sql",
  "markdown",
  "go",
  "rust",
  "docker",
  "properties",
  "diff",
];

const SPECS: Spec[] = [
  {
    kind: "esm",
    from: "node_modules/marked/lib/marked.esm.js",
    to: "marked.esm.js",
  },
  {
    kind: "esm",
    from: "node_modules/dompurify/dist/purify.es.mjs",
    to: "purify.es.mjs",
  },
  {
    // Prism core ships as a self-contained classic script that defines `Prism`.
    kind: "bundle",
    to: "prism.js",
    from: ["node_modules/prismjs/prism.js"],
    banner: "/* prismjs core (classic script; sets the global `Prism`) */",
  },
  {
    // Every language component is an independent IIFE extending global Prism,
    // so they can be concatenated into one file and loaded with one tag.
    kind: "bundle",
    to: "prism-languages.js",
    from: PRISM_LANGUAGES.map((lang) => `node_modules/prismjs/components/prism-${lang}.min.js`),
    banner:
      "/* prismjs language definitions (concatenated; must load after prism.js) */\n" +
      PRISM_LANGUAGES.map((lang) => `/* → ${lang} */`).join("\n"),
  },
  {
    // Mermaid ships one self-contained esbuild bundle that assigns itself to
    // `globalThis.mermaid`; the ESM build is split into lazy chunks we would not
    // be able to serve without a build step.
    kind: "bundle",
    to: "mermaid.min.js",
    from: ["node_modules/mermaid/dist/mermaid.min.js"],
    banner: "/* mermaid (classic script; sets the global `mermaid`) */",
  },
];

async function main(): Promise<void> {
  await mkdir(vendorDir, { recursive: true });
  const lines: string[] = [
    "# Vendored browser assets",
    "",
    "Generated by `npm run vendor` (`postinstall` runs it too). Do not edit by hand.",
    "Versions come from the devDependencies in package.json.",
    "",
    "Licenses (upstream license and notice are preserved at the top of each file):",
    "",
    "- `marked.esm.js` — [marked](https://github.com/markedjs/marked), MIT",
    "- `purify.es.mjs` — [DOMPurify](https://github.com/cure53/DOMPurify), Apache-2.0 OR MPL-2.0 (dual)",
    "- `prism.js`, `prism-languages.js` — [Prism](https://github.com/PrismJS/prism), MIT",
    "- `mermaid.min.js` — [Mermaid](https://github.com/mermaid-js/mermaid), MIT",
    "",
    "`mermaid.min.js` is ~3.4 MB; it is the only vendored asset that size, and it renders",
    "diagrams client-side so the server stays dependency-free.",
    "",
  ];

  for (const spec of SPECS) {
    const target = join(vendorDir, spec.to);

    if (spec.kind === "esm") {
      await copyFile(join(root, spec.from), target);
      const contents = await readFile(target, "utf8");
      assertSelfContained(spec.to, contents);
      lines.push(`- \`${spec.to}\` ← \`${spec.from}\` (${kb(contents)})`);
      process.stdout.write(`vendored ${spec.to} (${kb(contents)})\n`);
      continue;
    }

    const parts: string[] = [spec.banner, ""];
    for (const from of spec.from) {
      const contents = await readFile(join(root, from), "utf8");
      parts.push(`/* ---- ${from} ---- */`, contents.trimEnd(), "");
    }
    const bundle = `${parts.join("\n").trimEnd()}\n`;
    await writeFile(target, bundle, "utf8");
    assertNoModuleSyntax(spec.to, bundle);
    lines.push(`- \`${spec.to}\` ← ${spec.from.length} files (${kb(bundle)})`);
    process.stdout.write(`vendored ${spec.to} (${spec.from.length} files, ${kb(bundle)})\n`);
  }

  lines.push("");
  await writeFile(join(vendorDir, "README.md"), lines.join("\n"));
}

function kb(contents: string): string {
  return `${(contents.length / 1024).toFixed(1)} KB`;
}

/** Vendored ES modules must not import anything we do not serve. */
function assertSelfContained(name: string, contents: string): void {
  const imports = [...contents.matchAll(/^\s*import\s.+?from\s+["'](.+?)["']/gm)]
    .map((match) => match[1])
    .filter((specifier): specifier is string => Boolean(specifier));
  const external = imports.filter((specifier) => !specifier.startsWith("."));
  if (external.length > 0) {
    throw new Error(`${name} has external imports: ${external.join(", ")}`);
  }
}

/** Bundled vendor files are loaded as classic scripts, so they cannot use ESM. */
function assertNoModuleSyntax(name: string, contents: string): void {
  if (/^\s*(import|export)\s/m.test(contents)) {
    throw new Error(`${name} contains ESM syntax but is loaded as a classic script`);
  }
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(1);
});
